name: IronElevators
main: me.ScarleTomato.IronElevators.IronElevators
version: gbl 1.13 [mc1.13]
api-version: 1.13
description: >
             Easy Iron Block Elevators
permissions:
ironelevators.use:
  default: true
  description: Allow a player to teleport between elevators
